name: ofs-store
services:
  bucket:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - uploads_data:/usr/src/app/uploads
      - node_modules:/usr/src/app/node_modules
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  uploads_data:
  node_modules:
